### ISSUE TITLE
Update entries with same file name 

### ISSUE THREAD

**Issue by alfredoxyanez** [unicef/project-connect#1]
Add replacement file feature to Active Admin interface. I.e. if we add a file twice the database will update to the values of the file that was uploaded last.

**Comment by mikefab** [comment]
From @mfajardorua's email: "when uploading the same file (with the same name), could it erase all the registers from previous file version and push the ones from the new file?"

**Comment by mikefab** [comment]
The Rspec test framework has been added, so tests can accompany each feature.  I  implemented a solution for this feature, but then realized that it deletes records before CSV validation is complete. 

The test is here: https://github.com/unicef/project-connect/blob/master/spec/import_spec.rb

A better solution, probably, is, on "before_batch_import", check if file has been uploaded before and then assign a version number to records. Then on "after_batch_import" delete records with previous versions.

**Comment by mikefab** [comment]
Rspec has been added so I could add a test with the feature. My solution wasn't perfect as it deleted records with the same file name before passing validation.

**Comment by mikefab** [comment]
Actually, active_admin_import:before_batch_import rolls back and no records are deleted.

A test has been added to verify: 
Context: When csv with same name is uploaded twice
it 'should not replace old ones if file fails validation'

**Comment by mfajardorua** [comment]
It works fine. Good job
