### ISSUE TITLE
Naming Convention

### ISSUE THREAD

**Issue by mfajardorua** [unicef/project-connect#2]
**Naming convention** 
The FILE name to be uploaded through Active Admin should containing information on the 'owner', 'privacy_data'(0=public,1=private) and 'privacy_source'(0=public,1=private).

Name file will be : 'country_code'-'owner-'privacy_data'-'datasource_id'-'privacy_source'.csv

Example for Brasil for a Project Connect file with
public data from the Ministry of CTIC where the source should remain private:
"BR-ProCo-0-MCTIC-1.csv"

**Comment by mikefab** [comment]
Would like to change:

privacy_data to is_private
provider_is_private to private_source
datasource_id to provider.

Is that acceptable?

**Comment by mfajardorua** [comment]
privacy_data to "**is_private**" OK
I guess you mean the other way around:  private_source to "**provider_is_private**" then OK
datasource_id to "**provider**" OK

**Comment by mikefab** [comment]
Complete. Validation tests:

      expect(subject.errors.messages).to include(owner: ["can't be blank"])
      expect(subject.errors.messages).to include(country_code: ["is the wrong length (should be 2 characters)"])
      expect(subject.errors.messages).to include(is_private: ["is not included in the list"])
      expect(subject.errors.messages).to include(provider_is_private: ["is not included in the list"])

**Comment by mfajardorua** [comment]
It works. Thanks Mike
