### ISSUE TITLE
Update School Table schema

### ISSUE THREAD

**Issue by mikefab** [unicef/project-connect#3]
From @mfajardorua:
**Update School Table Schema**: the .xlsx file content the new fields to be added ('owner', 'privacy_data' and 'privacy_source' should be filled up with the "name file" information
[Fields_TB_added_schema.xlsx](https://github.com/unicef/project-connect/files/1228871/Fields_TB_added_schema.xlsx)

**Comment by mikefab** [comment]
In active_admin_import:before_batch_import hook, these values are parsed from file name.
Test: "should have format:  'country_code'-'owner-'privacy_data'-'datasource_id'-'privacy_source"

**Comment by mfajardorua** [comment]
new fields have been verified. Thanks
